Repository buttonmen-dev/buttonmen, pull requests merged in 2022-02, with the labels that each got.

#2840 Enable CustomBM on staging
  src/engine/BMInterfaceGame.php
  src/ui/js/Newgame.js
  test/src/api/responder00Test.php
Labels: dev site

#2835 Added Durer Rawg set
  deploy/database/data.button.sql
  deploy/database/updates/02507_rawg_01.sql
  src/engine/BMDieSwing.php
  src/ui/images/button/annalee.png
  src/ui/images/button/ashleyjay.png
  src/ui/images/button/bishop.png
  src/ui/images/button/bozo.png
  src/ui/images/button/brad.png
  src/ui/images/button/brenda.png
  src/ui/images/button/brent.png
  src/ui/images/button/cardie.png
  src/ui/images/button/cherry.png
  src/ui/images/button/chuck.png
  src/ui/images/button/cuddy.png
  src/ui/images/button/dave.png
  src/ui/images/button/derks.png
  src/ui/images/button/dickie.png
  src/ui/images/button/don.png
  src/ui/images/button/gorman.png
  src/ui/images/button/hedy.png
  src/ui/images/button/hunter.png
  src/ui/images/button/jamie.png
  src/ui/images/button/maggie.png
  src/ui/images/button/mattron.png
  src/ui/images/button/orry.png
  src/ui/images/button/portia.png
  src/ui/images/button/reilly.png
  src/ui/images/button/smoot.png
  src/ui/images/button/stamps.png
  src/ui/images/button/zedna.png
  test/src/api/responder00Test.php
  test/src/api/responderTestFramework.php
  tools/api-client/python/lib/random_ai.py
Labels: replay testing, dev site

#2838 Added various flavour texts
  deploy/database/data.button.sql
  deploy/database/updates/02659_flavour_text_01.sql
Labels: ready to merge, dev site

#2845 Use the --single-transaction flag to make backups less disruptive
  deploy/vagrant/modules/buttonmen/templates/backup_database.erb
Labels: ready to merge
