Repository buttonmen-dev/buttonmen, pull requests merged in 2022-01, with the labels that each got.

#2797 Install mod_pagespeed in lieu of custom timestamp-based versioning
  deploy/vagrant/modules/apache/manifests/init.pp
  deploy/vagrant/modules/apache/templates/mod_pagespeed.conf.erb
  deploy/vagrant/modules/buttonmen/manifests/init.pp
  deploy/vagrant/modules/buttonmen/templates/setup_ui_cache_links.erb
  src/ui/about.html
  src/ui/active_players.html
  src/ui/buttons.html
  src/ui/create_game.html
  src/ui/create_user.html
  src/ui/faq.html
  src/ui/forgot_password.html
  src/ui/forum.html
  src/ui/game.html
  src/ui/getting-started.html
  src/ui/help.html
  src/ui/history.html
  src/ui/index.html
  src/ui/js/Loader.js
  src/ui/open_games.html
  src/ui/prefs.html
  src/ui/privacy.html
  src/ui/profile.html
  src/ui/skills.html
  src/ui/verify.html
  src/ui/verify_reset.html
Labels: ready to merge, dev site

#2706 Added 2021 Fanatics
  deploy/database/data.button.sql
  deploy/database/updates/02346_2021fanatics_01.sql
  src/ui/images/button/bosco312.png
  src/ui/images/button/cycozar.png
  src/ui/images/button/gamerxyz.png
  src/ui/images/button/irilyth.png
  src/ui/images/button/scipio.png
  test/src/api/responder00Test.php
Labels: ready to merge, dev site

#2775 Reversed order of open games
  src/engine/BMInterface.php
Labels: ready to merge, dev site

#2666 Added Cybersuit Corp set (was Corpo World)
  deploy/database/data.button.sql
  deploy/database/updates/02664_corpo_world_01.sql
  deploy/database/updates/02664_corpo_world_02.sql
  src/ui/images/button/andrew.png
  src/ui/images/button/chad.png
  src/ui/images/button/fiona.png
  src/ui/images/button/gavin.png
  src/ui/images/button/isabel.png
  src/ui/images/button/monique.png
  src/ui/images/button/nadia.png
  src/ui/images/button/sachin.png
  test/src/api/responder00Test.php
Labels: replay testing, dev site

#2783 fix broken links
  src/ui/help/index.html
  src/ui/js/Login.js
  src/ui/js/Overview.js
  test/src/ui/js/test_Login.js
Labels: dev site

#2822 Updated broken links, part two (including removing old help page)
  src/ui/help/index.html
  src/ui/js/Env.js
  src/ui/js/Forum.js
  src/ui/js/Help.js
  src/ui/js/Overview.js
Labels: dev site

#2826 Correct calculation of trip attack validity vs Maximum Mood
  src/engine/BMAttackTrip.php
  test/src/engine/BMAttackTripTest.php
Labels: replay testing
